apiVersion: v1
kind: Service
metadata:
  name: graylog-service
  labels:
    name: graylog-service
  namespace: graylog
spec:
  selector:
    graylog: "true"
  ports:
  - name: http
    protocol: TCP
    port: 9000
  - name: tcp-input
    protocol: TCP
    port: 12201
  - name: http-input
    protocol: TCP
    port: 12202
  clusterIP: None