apiVersion: v1
kind: Service
metadata:
  name: graylog-slave
  labels:
    name: graylog-slave
spec:
  selector:
    role: graylog-slave
  ports:
  - name: http
    protocol: TCP
    port: 9000
  clusterIP: None